---
title: "STT1810 Basic Statistics<br>Textbook Learning Goals"
output: 
  html_document: 
    theme: yeti
    highlight: textmate
    toc: true
    toc_depth: 5
    toc_float: true
    css: "../../css/style.css"
    keep_md: yes
---

<hr>
### TEXTBOOK

The course textbook for STT1810 is [***Introduction to Statistical Investigations, 2nd Edition***](http://www.isi-stats.com/isi/index2nd.html) by Nathan Tintle, Beth Chance, George Cobb, Allan Rossman, Soma Roy, Todd Swanson, and Jill VanderStoep. You will have access to the textbook online via [WileyPLUS](https://www.wileyplus.com/).

We will use selected sections of the textbook to facilitate the **Course Learning Goals**.

1. Students will demonstrate effective use of selected descriptive statistics methods.
2. Students will demonstrate effective use of selected inferential statistics methods.
3. Students will effectively communicate using statistical frameworks and vocabulary.
4. Students will use statistical thinking to evaluate scholarly research and popular media.
5. Students will demonstrate preparedness for continued statistics coursework or research.

Participation in STT 1810 is also designed to meet the following [General Education Learning Goals]((https://universitycollege.appstate.edu/programs/general-education-program/program-goals)).

* Goal 1. Thinking Critically and Creatively
* Goal 2. Communicating Effectively

**You may use this as a checklist of knowledge and skills you need to acquire to be successful in this course.**


<hr>
### PRELIMINARIES

#### **Section P.1** Learning Goals

**Overall Goal: Use the six-step statistical investigation method to carry out any statistical study.**

* Describe how the six steps of a statistical investigation (the "Six-Step Method") apply to a particular statistical study.
* Think of / write research questions that could be investigated with a statistical study.
* Identify observational units / variables in a statistical study.
* Classify variables as categorical or quantitative.

#### **Section P.2** Learning Goals

**Overall Goal: Describe distributions of quantitative variables.**

* Describe the distribution of a quantitative variable in terms of shape, center, variability, and unusual observations.
* Compare shapes between two or more distributions that are displayed in dotplots or histograms.
* Compare the centers between two or more distributions that are displayed in dotplots or histograms.
* Compare the variability between two or more distributions in dotplots or histograms.
* Interpret graphs that contain a color-coded third variable.
* Make predictions about centers/means, and about variability / standard deviations, based on the context of the variable.

#### **Section P.3** Learning Goals

**Overall Goal: Use simulations to explore and understand probabilities.**

* Write an interpretation of a probability as a long-run proportion.
* Describe how to use physical devices such as coins and cards to simulate a random process.
* Conduct a simulation analysis to approximate a probability.
* Describe the effect of increasing the number of repetitions in a simulation analysis on the accuracy of an approximate probability (or a simulated probability distribution).
* Select an appropriate decision involving a random process, based on probabilities and/or simulation results.


<hr>
### CHAPTER 01

#### **Section 1.1** Learning Goals

**Overall Goal: Use the chance model to determine whether an observed statistic is unlikely to occur.**

* Recognize the difference between parameters and statistics.
* Describe how to use coin tossing to simulate outcomes from a chance model of a random choice between two events.
* Use the [ISI One Proportion applet](http://www.isi-stats.com/isi2nd/ISIapplets2021.html) to carry out a coin tossing simulation.
* Identify whether or not the results of a study are statistically significant and whether or not a chance model is a plausible explanation for the data.
* Implement the 3S strategy: find a statistic, simulate results from a chance model, and determine strength of evidence.
* Differentiate between saying a chance model is plausible and a chance model is the correct explanation for observed data (i.e., whether or not we have "proven" a result).

#### **Section 1.2** Learning Goals

**Overall Goal: Calculate and interpret a *p*-value, and state the strength of evidence it provides against the null hypothesis.**

* Use appropriate symbols for parameter and statistic.
* State the null and the alternative hypotheses in words and in terms of the symbol $\pi$, the long-run proportion.
* Explain how to conduct a simulation using a null hypothesis probability that is not 50-50.
* Use the [ISI One Proportion applet](http://www.isi-stats.com/isi2nd/ISIapplets2021.html) to obtain the *p*-value after carrying out an appropriate simulation.
* Anticipate the null distribution's center and how it changes based on using proportion or count as the statistic.
* Interpret the *p*-value and explain why a smaller *p*-value provides stronger evidence against the null hypothesis.
* State a conclusion about the alternative hypothesis and null hypothesis based on the *p*-value.

#### **Section 1.3** Learning Goals

**Overall Goal: Calculate a standardized statistic for a single proportion and evaluate the strength of evidence it provides against a null hypothesis.**

* Find a standardized statistic from the observed proportion of “successes” in the data, the hypothesized mean of the null distribution (i.e., *the value of the parameter that is specified in Ho*), and standard deviation (SD) of the null distribution as produced by the [ISI One Proportion applet](http://www.isi-stats.com/isi2nd/ISIapplets2021.html) (i.e., simulation).
* Interpret a standardized statistic.
* State a conclusion about the alternative hypothesis (and null hypothesis Ho) based on the magnitude of the standardized statistic.
* Recognize that standardizing the statistic is an alternative measure of strength of evidence.

#### **Section 1.4** Learning Goals

**Overall Goal: Describe how the distance of the observed statistic from the parameter value specified by the null hypothesis, sample size, and one- vs. two-sided tests affect the strength of evidence against the null hypothesis.**

* Anticipate and explain why, when everything else remains the same, the *p*-value is smaller when the observed proportion of successes is farther away from the hypothesized value of the long-run proportion of successes.
* Anticipate and explain why, when everything else remains the same, the *p*-value is smaller when the sample size is larger.
* Recognize when a two-sided test / alternative hypothesis is suggested by the research question.
* Anticipate and explain why, when everything else remains the same, the *p*-value is larger when the alternative hypothesis is two-sided.


<hr>
### CHAPTER 02

#### **Section 2.1** Learning Goals

**Overall Goal: Describe how to select a random sample and predict sampling distributions for a sample proportion.**

* Identify parameters (long-run proportion) and statistics (sample proportion) in a statistical study.
* Identify which statistics (proportions) and graphs (bar graph) are appropriate for categorical variables, construct graphs and calculate statistics with use of technology, and interpret appropriately.
* Identify the (finite) population and the sample in a statistical study.
* Identify whether a sampling method is likely to be biased and explain the potential impact.
* Describe how to select a random sample and recognize that one advantage of a random sample is that it is likely to be representative of the population regardless of sample size.
* Fill in a data table where rows are the observational units and columns are the variables.
* Predict the mean, standard deviation, and shape of the sampling distribution of a sample proportion from a random sample of size n, where the population proportion  is known.
* Apply simulation-based inference methods for a population proportion to research studies involving random samples from finite populations.
* Identify whether a study may be impacted by non-sampling concerns and explain the potential impact.


<hr>
### CHAPTER 03

**Overall Goal: Construct and interpret a confidence interval for a single population proportion using the range of plausible values technique.**

#### **Section 3.1** Learning Goals

* Complete multiple two-sided tests of significance, using the same value for the sample proportion but changing the value under the null hypothesis, and obtain an interval of plausible values for the population parameter.
* Interpret an interval of plausible values as estimating the population parameter and as a confidence interval.
* Based on the results of a test of significance, infer whether or not a value is in the confidence interval and vice versa.

#### **Section 3.2** Learning Goals

**Overall Goal: Construct and interpret a confidence interval for a single population proportion using the 2SD method.**

* Compute a confidence interval for a proportion written in terms of its endpoints vs. a confidence interval written in terms of center plus or minus a margin of error.
* Approximate a 95% confidence interval for a proportion by using the 2SD method.

#### **Section 3.4** Learning Goals

**Overall Goal: Identify how factors (confidence level, sample size, SD) affect the width of the confidence interval.**

* Recognize that all other things being equal, as the confidence level increases, the width of the confidence interval increases.
* Apply the idea that the confidence level of an interval corresponds to its coverage probability (*the proportion of confidence intervals containing the true parameter value across many, many random samples*) in the interpretation of confidence intervals.
* Recognize that all other things being equal, as the sample size increases, the width of the resulting confidence interval decreases.
* Recognize that all other things being equal, as the sample proportion gets farther from 0.5, standard error decreases and thus a resulting confidence interval will be narrower.
* Recognize that statistical significance on its own does not imply evidence of a large difference from Ho. This issue is especially relevant with large sample sizes. 
* Know that *p*-values address statistical significance while CIs help assess the plausible size of the parameter.


<hr>
### CHAPTER 04

#### **Section 4.1** Learning Goals

**Overall Goal: Identify confounding variables in observational studies.**

* Calculate and interpret conditional proportions.
* Interpret conditional proportions as to whether they give any indication of an association between the explanatory and response variables.
* Identify which variable is the explanatory variable and which is response in a study involving two variables.
* Identify potential confounding variables and explain how they provide an alternative explanation for the observed association between the explanatory variable and the response variable.
* Draw a diagram to show how the confounding variable provides an alternative explanation for the observed association between the explanatory variable and the response variable.

#### **Section 4.2** Learning Goals

**Overall Goal: Explain how studies using random assignment are able to draw cause-and-effect conclusions.**

* Identify a study as observational or experimental.
* Explain that random assignment gives us the ability to draw cause–effect conclusions because it ensures that treatment groups have similar characteristics.
* Identify whether a study uses random assignment and/or random sampling and the implications of these design decisions on the conclusions that can be drawn.
* Describe what a block study design is and the benefits of using a blocking variable.


<hr>
### CHAPTER 05

#### **Section 5.1** Learning Goals

**Overall Goal: Compare two sample proportions numerically and graphically.**

* Organize counts into a two-way table, when data are available on two categorical variables for the same set of observational units.
* Calculate conditional proportion of successes, for different categories of the explanatory variable, and use these conditional proportions to decide whether there is preliminary evidence of an association between the explanatory and response variables.
* Create a segmented bar chart or mosaic plot to display data available on two categorical variables for the same set of observational units.
* Calculate and interpret relative risk (also called risk ratio).

#### **Section 5.2** Learning Goals

**Overall Goal: Carry out a simulation-based analysis to investigate the difference between two population proportions.**

* State Ho and Ha in terms of “no association” versus “there is an association” as well as in terms of comparing probabilities of success for two categories of explanatory variable ($\pi_1$ and $\pi_2$) when exploring the relationship between two categorical variables.
* Implement the 3S strategy: find a statistic, simulate the null distribution, and compute the strength of evidence...
* Describe how to use cards to simulate what outcomes (in terms of difference in conditional proportions and/or relative risk) are to be expected in repeated random assignments, if there is no association between the two variables.


<hr>
### CHAPTER 06

#### **Section 6.1** Learning Goals

**Overall Goal: Compare two sample means numerically and graphically.**

* Calculate or estimate the mean, median, quartiles, five number summary, and interquartile range from a dataset and understand what these are measuring.
* When comparing two quantitative distributions, identify which has the larger mean, median, standard deviation, and inter-quartile range.
* Identify whether there is likely an association between a binary categorical variable and a quantitative response variable.

#### **Section 6.2** Learning Goals

**Overall Goal: Carry out a simulation-based analysis to investigate the difference between two population means.**

* State the null and the alternative hypotheses in terms of “no association” versus “there is an association” as well as in terms of comparing means (i.e., $\mu_1$ and $\mu_2$) for an explanatory variable with two categories.
* Implement the 3S strategy to compare two means: find a statistic, simulate, and compute the strength of evidence against observed study results happening by chance alone.
* Describe how to use cards to simulate what outcomes (in terms of difference in means or median) are to be expected in repeated random assignments, if there is no association between the two variables.
* Use the [ISI Multiple Means applet](http://www.isi-stats.com/isi2nd/ISIapplets2021.html) to conduct a simulation of the null hypothesis and be able to read the applet's output.


<hr>
### CHAPTER 07

#### **Section 7.1** Learning Goals

**Overall Goal: Identify a study design as paired using repeated measures or paired using matching.**

* Identify a study design as having pairing or independent groups.
* Identify a study design as paired using repeated measures or paired using matching.

#### **Section 7.2** Learning Goals

**Overall Goal: Perform and interpret a simulation-based analysis of paired data for a quantitative response.**

* Understand the difference between independent samples and paired samples in terms of the study design and how variability can be lower in a paired design and how this can influence the strength of evidence.
* Complete a simulation-based test of significance of a paired design by writing out the hypothesis, determining the observed statistic, computing the p-value, and writing out an appropriate conclusion.


<hr>

Updated `r format(Sys.time(), "%A, %B %d, %Y @ %I:%M %p")`

