---
title: "STT1810 --- Section P.3<br>Random Processes"
subtitle: "Introduction to Statistical Investigations, 2^nd^ Edition"
author: "Author: Jill E. Thomley // Appalachian State University"
date: "Last updated `r format(Sys.time(), '%A, %B %d, %Y @ %I:%M %p')`"
output: 
  ioslides_presentation:
    logo: images/logoASU.jpg
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  comment = NA
)
```


## Before We Begin…

These slides are intended to accompany Section P.3 Exploring Random Processes in [*Introduction to Statistical Investigations, 2nd Edition*](http://www.isi-stats.com/isi/index2nd.html). 

*This content does not replace reading the textbook section.* It is for class presentation and reference.

See Also:

* Glossary of ISI Textbook Vocabulary on AsULearn
* [Section P.1 Introduction to the Six-Step Method](https://stat-jet-asu.github.io/STT1810BasicStatistics/Slides/CHP_1.html)
* [Section P.2 Exploring Data](https://stat-jet-asu.github.io/STT1810BasicStatistics/Slides/CHP_2.html)
* Exploration P.3 Cars or Goats (TBA)


## Learning Goals for Preliminaries

* Use the six-step statistical investigation method to carry out any statistical study. [Section P.1]
* Describe distributions of quantitative variables. [Section P.2]
* Use simulations to explore and understand probabilities. [Section P.3]

  *We will use these investigative methods throughout the course.* 

<hr>

One more important goal of this (and every other) section is for you to learn the vocabulary of statistical investigations/thinking. 

You need to **"speak the language"** to understand what is being taught in class, and also to express ideas that will demonstrate your understanding and proficiency with the material. 


## Learning Goals for Section P.3

* Write an interpretation of a probability as a long-run proportion.
* Describe how to use physical devices such as coins and cards to simulate a random process.
* Conduct a simulation analysis to approximate a probability.
* Describe the effect of increasing the number of repetitions in a simulation analysis on the accuracy of an approximate probability (or a simulated probability distribution).
* Select an appropriate decision involving a random process, based on probabilities and/or simulation results.


## Section P.3 New Vocabulary

* probability

* probability distribution

* random process

* simulation

When we talk about probabilities and distributions, we need to keep in mind the distinction between what is **possible** (what *can* happen) and what is **probable** (more or less *likely* to happen). 

* If something is *impossible*, its probability is 0. 
* If something is *certain* to happen, its probability is 1.
* Something that is *possible* has a probability between 0 and 1.


## Definitions

**process:** an endless series of potential observations (just about anything we want to explore can be thought of as a process)

**random process:** a process that has unknown individual (short-term) outcomes but a long-run pattern of outcomes; we explore these patterns through repeated observation

**probability:** the long-run proportion of times an outcome from a random process occurs; probability is the language we use to characterize random processes

**probability distribution:** the long-run pattern of outcomes from a random process

**simulation:** an artificial re-creation of a random process using a computer or tactile tools such as coins, dice, cards, or spinners


## TBA---more about probability

