---
title: "STT 1810---Textbook Chapter 02 Learning Goals"
output: 
  html_document: 
    theme: yeti
    highlight: textmate
    css: "../css/style.css"
    keep_md: yes
---

<hr>

The course textbook for STT 1810 is [***Introduction to Statistical Investigations, 2nd Edition***](http://www.isi-stats.com/isi/index2nd.html) by Nathan Tintle, Beth Chance, George Cobb, Allan Rossman, Soma Roy, Todd Swanson, and Jill VanderStoep. Students have access to the textbook online via [**WileyPLUS**](https://www.wileyplus.com/). We will cover the following sections in STT 1810.

<hr>

### CHAPTER 02 *Generalization: How Broadly Do the Results Reply?*

#### **Section 2.1** Sampling from a Finite Population: Proportions

**Chapter Learning Goal: Describe how to select a random sample and predict sampling distributions for a sample proportion.**

**Section Learning Goals:**

* Identify parameters (long-run proportion) and statistics (sample proportion) in a statistical study.
* Identify which statistics (proportions) and graphs (bar graph) are appropriate for categorical variables, construct graphs and calculate statistics with use of technology, and interpret appropriately.
* Identify the (finite) population and the sample in a statistical study.
* Identify whether a sampling method is likely to be biased and explain the potential impact.
* Describe how to select a random sample and recognize that one advantage of a random sample is that it is likely to be representative of the population regardless of sample size.
* Fill in a data table where rows are the observational units and columns are the variables.
* Predict the mean, standard deviation, and shape of the sampling distribution of a sample proportion from a random sample of size n, where the population proportion is known.
* Apply simulation-based inference methods for a population proportion to research studies involving random samples from finite populations.
* Identify whether a study may be impacted by non-sampling concerns and explain the potential impact.

<hr>

Updated `r format(Sys.time(), "%A, %B %d, %Y @ %I:%M %p")`

