---
title: "STT 1810 Course Content & Resources"
subtitle: "Text: *Introduction to Statistical Investigations, 2^nd^ Edition*"
author: "Instructor: Jill E. Thomley"
output: 
  html_document: 
    theme: cosmo
    highlight: textmate
    toc: true
    toc_depth: 3
    css: "../../css/style.css"
    keep_md: yes
---

<hr>

### Section P.1 Intro to the Six-Step Method

#### Videos
* SLP: [Intro to Statistics](https://youtu.be/MXaJ7sa7q-8) (4:49)
* CCS: [What Is Statistics?](https://youtu.be/sxQaBpKfDRk) (12:59)
* CCS: [Mathematical Thinking](https://youtu.be/tN9Xl1AcSv8) (11:00)

#### Applets
* None -- ESP Test?

#### Slides
* JET: [Section P.1 Slides](https://stat-jet-asu.github.io/STT1810BasicStatistics/Slides/Chapter00/CHP_1.html)
* JET: [Example P.1 Slides](https://stat-jet-asu.github.io/STT1810BasicStatistics/Slides/Chapter00/ExampleP_1.html)
* JET: [ESP Activity Slides](https://stat-jet-asu.github.io/STT1810BasicStatistics/Slides/ChapterXX/ESPZenerCards.html)

<hr>

### Section P.2 Exploring Data

#### Videos
* CCS: [Measures of Central Tendency](https://youtu.be/kn83BA7cRNM) (11:22)
* CCS: [Measures of Spread](https://youtu.be/R4yfNi_8Kqw) (11:46)
* CCS: [Data Visualization Part 1](https://youtu.be/hEWY6kkBdpo) (10:21)
* CCS: [Data Visualization Part 2](https://youtu.be/HMkllhBI91Y) (11:35)
* CCS: [The Shape of Data](https://youtu.be/bPFNxD3Yg6U) (11:22)
* SLP: [Bar Charts, Histograms, Stemplots, Timeplots](https://youtu.be/uHRqkGXX55I) (7:34)
* SLP: [Mode, Median, Mean, Range, and SD](https://youtu.be/mk8tOD0t8M0) (7:19)
* SLP: [The Effects of Outliers on Spread and Centre](https://youtu.be/vcbMinm_1Q8) (4:32)

#### Applets
* ISI2: [Descriptive Statistics](https://www.isi-stats.com/isi2nd/ISIapplets2021.html)

#### Slides
* JET: [Section P.2 Slides](https://stat-jet-asu.github.io/STT1810BasicStatistics/Slides/Chapter00/CHP_2.html)
* JET: [Example P.2 Slides](https://stat-jet-asu.github.io/STT1810BasicStatistics/Slides/Chapter00/ExampleP_2.html)

<hr>

### Section P.3 Exploring Random Processes

#### Videos
* CCS: [Randomness](https://youtu.be/jL9en6NvQfk) (12:06)

#### Applets
* ISI2: [Monty Hall Game](https://www.isi-stats.com/isi2nd/ISIapplets2021.html) applet
* SEF: [Advanced Monty Hall](https://shodor-education.github.io/interactivate/activities/AdvancedMontyHall/#gsc.tab=0)
* SEF: [Adjustable Spinner](https://shodor-education.github.io/interactivate/activities/AdjustableSpinner/#gsc.tab=0)

#### Slides
* TBA

<hr>

### Section 1.1 Introduction to Chance Models

<hr>

### Section 1.2 Measuring Strength of Evidence

<hr>

### Section 1.3 Alternative Measure of Strength of Evidence

<hr>

### Section 1.4 What Impacts Strength of Evidence?

<hr>

### Section 2.1 Sampling from a Finite Population: Proportions

<hr>

### Section 2.2 (Sampling With) Quantitative Data

<hr>

### Section 3.1 Statistical Inference: Confidence Intervals

<hr>

### Section 3.2 2SD Confidence Intervals for a Single Proportion

<hr>

### Section 3.4 Factors That Affect the Width of a Confidence Interval

<hr>

### Section 4.1 Association and Confounding

<hr>

### Section 4.2 Observational Studies Versus Experiments

<hr>

### Section 5.1 Comparing Two Groups: Categorical Response

<hr>

### Section 5.2 Comparing Two Proportions: Simulation-Based Approach

<hr>

### Section 6.1 Comparing Two Groups: Quantitative Response

<hr>

### Section 6.2 Comparing Two Means: Simulation-Based Approach

<hr>

### Section 7.1 Paired Designs (for Data Collection)

<hr>

### Section 7.2 Simulation-Based Approach to Analyzing Paired Data

<hr>

### Abbreviations

* CCS: [CrashCourse: Statistics](https://www.youtube.com/@crashcourse) YouTube channel
* ISI2: [*Introduction to Statistical Investigations, 2nd Edition*](https://www.isi-stats.com/isi/index2nd.html)
* JET: Materials created by Jill E. Thomley, PhD
* SEF: [The Shodor Education Foundation, Inc.](http://www.shodor.org/)
* SLP: [Simple Learning Pro](https://www.youtube.com/@Simplelearningpro) YouTube channel


Test add



Updated `r format(Sys.time(), "%A, %B %d, %Y @ %I:%M %p")`

