---
title: "STT 1810 Basic Statistics<br>Syllabus for Fall 2024<br>Revised October 21, 2024"
output: 
  html_document: 
    theme: cosmo
    highlight: textmate
    toc: true
    toc_depth: 5
    css: "../../css/style.css"
    keep_md: yes
---

<hr>

#### **Instructor Information** 

Dr. Jill E. Thomley<br>
Walker Hall 228<br>
828-773-3273<br>
thomleyje@appstate.edu<br>
<https://jillthomley.github.io/>

#### **Bulletin Description**  

STT 1810 is an introduction to statistical problem solving. Topics include organization and presentation of data; measures of location, variation, and association; the normal distribution, sampling distributions, and statistical inference. Emphasis will be on conceptual understanding and interpretation of results rather than theoretical development. Statistical software will be utilized in the analysis of data and in the development of statistical and probabilistic concepts. STT 1810 is not open to students with credit for STT 2810, STT 2820, STT 3850, or STT 4811. (NUMERICAL DATA; COMPUTER; *GEN ED: Quantitative Literacy*)

Prerequisite: MAT 1010 or higher. Demonstrated readiness for college-level math. 

#### **Course Learning Goals**

1. Students will demonstrate effective use of selected descriptive statistics methods.
2. Students will demonstrate effective use of selected inferential statistics methods.
3. Students will effectively discuss the roles of randomness in statistical processes.
4. Students will effectively communicate using statistical frameworks and vocabulary.
5. Students will use statistical thinking to evaluate scholarly research and popular media.
6. Students will demonstrate preparedness for continued statistics coursework or research.

Participation in STT 1810 is also designed to meet the following [General Education Learning Goals]((https://irap.appstate.edu/GenEd_Goals)).

* Goal 1: Thinking Critically and Creatively
* Goal 2: Communicating Effectively
* Goal 3: Quantitative Literacy

Each textbook chapter and section we cover also has [focused goals](https://stat-jet-asu.github.io/STT1810BasicStatistics/SyllabusSchedule/Fall2024/STT1810F24CourseLearningGoals.html) that will be used in assessments.

#### **Class Meetings & Attendance**

* Section 102 will meet Tuesdays and Thursdays from 12:30 pm to 1:45 pm in Walker Hall 307B computer lab.
* Section 101 will meet Tuesdays and Thursdays from 2:00 pm to 3:15 pm in Walker Hall 307B computer lab.

As stated in the ASU Undergraduate Bulletin, “class attendance is an important part of a student’s educational experience. Students are expected to attend every meeting of their classes and are responsible for class attendance. Regardless of what reasons there may be for absence, students are accountable for all academic activities, and faculty may require special work or tests to make up for the missed class or classes.” 

**I will take class attendance for administrative and recordkeeping purposes, but I will *not* directly include attendance in your final grade.**

Our face-to-face time is only 2.5 hours (sometimes less) each week over 29 class periods, so it is important that your attention be focused on what we are doing in class. There are some additional guidelines to help facilitate the face-to-face learning experience for you and your peers.

* Do all necessary preparation for class, such as textbook readings and videos.
* Participate fully in all active learning activities, both individual and in groups.
* Be ready to participate when class starts (e.g., notebooks and materials out).
* Do not pack up at the end of class until I am finished teaching and dismiss you.
* Put away phones. Do not text, check email, surf the web, or do other coursework.

#### **Course Communication**  

* I will use the **Course Announcements** forum on our AsULearn site to send out announcements and course information. You are responsible for knowing the content of all postings, in addition to anything I say in class. 
* Except for major emergencies, all written communication must be handled through your **Private Forum on AsULearn**. I prefer this method because it stores all course-related messages and conversations in a place where we can easily access them throughout the semester. Like e-mail, you can include images and attachments. These forums keep my student/class communications separate from the rest of my email and provide notifications in AsULearn&mdash;a system I have found to be highly effective over the past few years. 
* Monday through Friday, I typically will check our AsULearn Private Forums for messages at least once per day between the hours of 10:00 am and 7:00 pm. I may check more than once on weekdays, since I am often on AsULearn grading or updating. I will try to check forums at least once on Saturdays, depending on my weekend schedule. Please do not expect replies on Sundays.

#### **Student Help Hours** 

* **MON:** None, but I will check Private Forum messages
* **TUE:** 11:00 am to 12:00 pm (WA 228 or Zoom)
* **WED:** 2:00 pm to 3:00 pm (Zoom only)
* **TUE:** 11:00 am to 12:00 pm (WA 228 or Zoom)
* **FRI:** None, but I will check Private Forum messages
* *I may schedule student appointments at other times, if needed.*

You may drop in or [book an appointment](https://calendar.google.com/calendar/u/0/selfsched?sstoken=UU0zQUk4blgtNW44fGRlZmF1bHR8Y2EyZDZmYTMxNmZjMWEwMjdiMzE0ZjQ1MmEwNDFjMmE). Appointments will take priority over drop-ins in terms of time. You may find yourself in a Zoom waiting room if I am interacting with an appointment, but I *will* get to you.

**Other Assistance:** I urge any student who has difficulty affording groceries or accessing sufficient food to eat every day, or who lacks a safe and stable place to live, to contact the Dean of Students (https://deanofstudents.appstate.edu/) for assistance and support. The Mountaineer Food Hub & Free Store (https://sustain.appstate.edu/initiatives/food-pantry/) is a free resource with pantry and personal care items. See the **Campus Resources for Students** link on our AsULearn page for more resources available to ASU students.

**Title IX Information Disclosure:** I care about you inside and outside of my classroom, and I want you to get the help and support you need. Given my role as an instructor at Appalachian State University, you should be informed about your choices regarding disclosure of sensitive information. If a student tells an instructor that they have experienced an act of interpersonal violence, then that faculty member is **required** to report it to the campus Title IX Coordinator. If you prefer to speak to someone who can keep your conversations confidential, I recommend the Counseling Center (828-262-3180, https://counseling.appstate.edu/). They also offer walk-in and after-hours coverage.

#### **Assessment & Grading**

##### **Text & Technology**

The course textbook is ***Introduction to Statistical Investigations (2nd edition)*** by Nathan Tintle, Beth Chance, George Cobb, Allan Rossman, Soma Roy, Todd Swanson, and Jill VanderStoep. Access to the textbook is included in your rental system fee and you will be done electronically via WileyPLUS. All course materials will be found either on [AsULearn](https://asulearn.appstate.edu/) (our primary course hub) or [WileyPLUS](https://www.wileyplus.com/).

**All of our class meetings will be held in a computer lab.** To participate in learning activities and to complete assignments outside of class, you will need access to an updated electronic device on which you can access Zoom, WileyPLUS, the simulation applets that accompany the textbook, and other electronic materials. The applets can be used on a cell phone, tablet, or computer. In general, a larger tablet or computer is better. 

##### **Assessment Items**

The only way to learn statistics is to **DO** statistics. Reading the textbook, watching the assigned videos, learning the vocabulary, and practicing the methods with software and data are critical to your learning and success. Our class activities and formative / summative assessments have been structured with these principles in mind. It will be easier to participate if you acquire some familiarity with the vocabulary and methods *before* we start to discuss and use them. You must "speak the language" of statistics to effectively demonstrate your knowledge. 

<p style = "color: red;">**Summary of Changes:** <u>*ADDED*</u> --- Pre-Closure Review assignment and Cumulative Final Assessment. <u>*DELETED*</u> --- Section 2.2 Practice Problems, Research/Media Analyses, and Final Cumulative Investigation. <u>*CHANGED*</u> --- percentage weighting for Practice Problems (30% to 35%), Chapter 1 Investigation (5% to 8%), Chapters 2 & 3 Investigation (8% to 12%), and Chapters 4 & 5 Investigation (12% to 20%).</p>

* **Practice Problems (35%):** These WileyPLUS assignments are primarily short, *formative* assessments on the current materials, designed to reinforce recently-introduced concepts and help you figure out where you need to review or seek additional help. On each assignment, you will get three tries per question. You will receive full credit (100%) if you earn **85%** or more of the possible points on a given assignment. If you earn between 60% and 85% of the possible points, your credit will be that percentage. If you earn less than 60% of the possible points, you will get no credit (0). Points earned will be calculated in WileyPLUS; credit will be manually entered into AsULearn. Late submissions are allowed through the end of the semester, for reduced points/credit. 

* **Pre-Closure Review (5%):** This WileyPLUS assignment will contain content we covered prior to the University closure---the Preliminaries, Section 1.1, and Section 1.2. You will receive full credit (100%) if you earn **90%** or more of the possible points on a given assignment. If you earn between 60% and 90% of the possible points, your credit will be that percentage. If you earn less than 60% of the possible points, you will get no credit (0). Points earned will be calculated in WileyPLUS; credit will be manually entered into AsULearn. **This assignment will be due November 05.** Late submissions are allowed through the end of the semester, for reduced points/credit. 

* **Cumulative Final Assessment (10%):** This WileyPLUS assignment will include material from all sections that we cover this semester. It will be made available to students on the Tuesday before the Thanksgiving break (November 26) and be **due December 10** (the final exam day for Section 102). Details on points will be made available before the assignment opens. ***We will not meet in person for final exams. This is a more flexible asynchronous assessment that replaces the original Final Cumulative Investigation.***

* **Chapter Investigations (45%):** You will complete several cumulative guided investigations that apply course material in a different context than the in-class explorations or WileyPLUS practice problems. These assignments will require you to work independently, integrate course concepts across chapters, and explain statistical ideas in your own words using appropriate statistical vocabulary. You will submit these via AsULearn and they will be scored using a rubric. More information will be provided on AsULearn.

    * Preliminaries Investigation **(5%)**
    * Chapter 1 Investigation **(8%)** --- tentatively due November 05
    * Chapters 2 & 3 Investigation **(12%)** --- tentatively due November 19
    * Chapters 4 & 5 Investigation **(20%)** --- due December 10
<p></p>

* **Research Ethics (5%):** Society benefits from research and decision-making that is supported by ethical statistical practice. All people who engage in research are expected to follow ethical guidelines and encourage others to do the same. Unfortunately, this has not always been the case. You will complete the type of online training required of anyone at Appalachian State University who wishes to engage in human subjects research, and questions related to ethics may appear in other assignments. More information will be provided on AsULearn.

##### **Grading Scale** 

This course will use the standard 10-point +/- grading scale (93--100 = A, 90--92 = A--, 87--89 = B+, etc.) to determine final grades. I do not round up. Accommodations *may* be made for documented extenuating circumstances that prevent you from completing work early/on time. Grades will be kept on [AsULearn](https://asulearn.appstate.edu/). You should monitor your grades throughout the term to make sure they are complete and accurate. Contact the instructor via your Private Forum or office hours if you have questions.   

##### **Sharing Materials**

All course materials may be subject to intellectual property protections under applicable law and regulation, including videos and slides. They are for the sole use of students enrolled in this class. Students **may** copy or record materials for personal use and study in the context of this class, but students **do not** have permission to share any class materials in any manner, on any platform, without the prior express permission of the faculty member teaching this course. When in doubt, *ask first*.

##### **Academic Integrity**

Appalachian's [Academic Integrity Code](https://academicintegrity.appstate.edu/) is designed to create an atmosphere of trust, respect, fairness, honesty, and responsibility. All members of the ASU community are responsible for promoting an ethical learning environment. Students attending ASU agree to abide by the following:

* Students will not lie, cheat, or steal to gain academic advantage.
* Students will oppose every instance of academic dishonesty.

**Instructions regarding student collaboration and the use of AI in course assignments will be given on a per-assignment basis on AsULearn.**

By submitting work under your name, you are attesting that you have abided by the Academic Integrity Code. Violations of Academic Integrity will be treated very seriously. [Penalties](https://academicintegrity.appstate.edu/pagesmith/13) can include a reduced grade for the assignment or course, course, academic probation, or expulsion.

#### **Student Expectations**

##### **Engage with the Content**

**Be proactive and take charge of your own learning!** Appalachian students are expected to make engagement with courses their first priority. If you have not done the assigned textbook readings and other class prep assignments before coming to class, or if you have not tried the problems on WileyPLUS or other assignments before coming to office hours, you likely will be confused, feel lost, and have a poor experience in this course. I DO NOT WANT THAT TO HAPPEN! Please help me to help you.

Each of you has the capability to succeed in STT 1810. However, sometimes we have to change certain behaviors, study habits, and/or emotional reactions to achieve that success. In this course, you will be challenged with concepts and problems you have never seen before. I do not expect you to be able to understand them all immediately. A critical first step in learning new material is seeing what you can do on your own. This may feel uncomfortable and frustrating. Success in statistics is not based on whether it "comes naturally" to you or whether a topic seems “clear” the first time you are introduced to it. Instead, success is about learning to use mistakes and material we may be struggling with to grow. Each time we get stuck, it teaches us something about the problem we are working on and leads us to develop greater skill and better understanding of the content---a firm foundation for the next layer of course material. 

##### **Invest Appropriate Time**

As per the University-wide Statement on Student Engagement with Courses (see University Policies below), you should expect to spend 2-3 hours on course work outside class for every hour you spend in class. **STT 1810 is a 3-credit course, which means course work and assessments are structured around 3 hours of class attendance and 6-9 hours of outside work per week.** All students are different, but I have used the [Rice Course Workload Estimator](https://cte.rice.edu/workload) and other tools to help estimate how long assigned course activities will take. If you find that you are spending fewer hours than these guidelines suggest, you can probably improve your understanding and grade by studying more. If you are consistently spending more hours than these guidelines suggest, you may be studying inefficiently; in that case, you should come see me to help identify where you can make some changes. Many students work during the school year to finance their educations; however, that does not change the requirements of this (or any) course. Budget your time accordingly and pace yourself to maximize your learning and achievement. 

##### **Communicate with Others**

Knowing what you can do on your own is important, but in the real world, people are not generally expected to work alone. In fact, teamwork is frequently required to achieve good outcomes. You will be expected to share with your peers to help develop your own and their proficiencies. I encourage you to talk to me and to your classmates in person or electronically even when you are not specifically assigned by me to do so. Asking questions and explaining things to others is one of the best ways to improve your understanding. Together we will create an environment in which everyone is respectful to one another and feels comfortable asking questions, making mistakes, and offering good guesses. Explore concepts and write out your thinking in a way that can be shared with others. Try everything that is asked of you, even if only to say, “I do not understand such and such” or “I am stuck here.” Be as specific as possible. *Consider. Conjecture*. I will try to give you hints and direction to help you understand. At times though, to encourage the exploration process, I may direct you to rethink a problem and then come back to discuss it with me  afterwards. This occurs when I believe that the struggle to understand is imperative for your deep understanding.  

##### **Additional Class Policies**

This course conforms to all Appalachian State University policies with respect to academic integrity, disability services, and class attendance. The details of these policies may be found at <http://academicaffairs.appstate.edu/resources/syllabi>.

**OVERALL CLASS ENVIRONMENT**: As per [AppalachianState University](https://diversity.appstate.edu/) and the [Department of Mathematical Sciences Statement on Diversity and Inclusiveness](https://mathsci.appstate.edu/diversity), I intend this class is to be a welcoming environment where everyone can learn and explore in order to achieve their full potential. As such, we all need to be respectful to each other in all interactions, regardless of gender, political party, race, religion, sexuality, disability, etc. This includes others' choices about COVID precautions, such as masks and social distancing. Activities that distract or disrupt your fellow students or the instructor may result in a lowered grade. First offenses typically will be dealt with by the instructor. Subsequent or serious behavior issues will be referred to the **Office of Student Conduct** (https://studentconduct.appstate.edu/).

<hr>

Updated `r format(Sys.time(), "%A, %B %d, %Y @ %I:%M %p")`

